---
abstract: 'XML::LibXML alternative to XML::Simple::XMLin()'
author:
  - 'Mark Overmeer <markov@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-LibXML-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: '0'
  Test::More: '0.54'
  XML::LibXML: '1.64'
resources:
  homepage: http://perl.overmeer.net/CPAN/
  license: http://dev.perl.org/licenses/
  repository: https://github.com/markov2/perl5-XML-LibXML-Simple.git
version: '1.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.011'
